import Head from 'next/head';
import React, { FC } from 'react';
import { IHomePage } from './HomePage.type';
import { MdOutlineContentCopy } from 'react-icons/md';
import { Box } from '@mui/system';
import GradientContainer from '@components/default/GradientContainer';

const HomePage: FC<IHomePage> = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box height='100vh' sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
				<GradientContainer paddingY='8px' paddingX='16px' width='500px' height='100px'>
					<></>
				</GradientContainer>
			</Box>

			<footer></footer>
		</div>
	);
};

export { HomePage };
